import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const customStyles = {
  fontFamily: 'Work Sans, sans-serif',
  letterSpacing: '-.5px',
  fontWeight: '100'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={customStyles}>{children}</body>
    </html>
  )
}
