import './globals.css'
import localFont from 'next/font/local'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const sfMono = localFont({src: '../public/sf-mono/SFMonoLight.otf'})
const majorMono = localFont({src: '../public/MajorMonoDisplay-Regular.ttf'})

const customStyles = {
  letterSpacing: '-1.5px',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={majorMono.className}>
      <body style={customStyles}>{children}</body>
    </html>
  )
}
