import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const customStyles = {
  fontFamily: 'Share Tech Mono, monospace',
  letterSpacing: '.01px'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={customStyles}>{children}</body>
    </html>
  )
}
